setwd("p:/obrien/biotelemetry/md wea habitat/wea-analysis")
rec<-readRDS("rec_events.rds")
library(dplyr)
glimpse(rec)
View(rec)
rec<-subset(rec,select=-c(9:11))
j <- filter(rec,Description=="Average temperature")
class(j$Data)
j$Data<-as.numeric(j$Data)
hist(j$Data)
ggplot(data=j,aes(x=Date.Time,y=Data,group=Site,colour=Site))+geom_line()+geom_point()